

server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: electronic_device_shop
  profiles:
    active: ${ENV:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/movie_website}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-id
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URI:http://localhost:8080}/realms/${PROFILE_REALM:thai_realm}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080}/realms/${PROFILE_REALM:thai_realm}

common:
  permit-all-path-patterns:
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /api/v1/user/login
    - /test/**
  cors:
    origins:
      - http://localhost:8081
      - http://localhost:3000

#thai:
#  name: thai
#  age: 18
#  clazz:
#    name: lop 1
#    ten-giao-vien: giao vien 1
#  levels:
#    - mot
#    - hai
#    - ba


keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:8080}
  realm: ${PROFILE_REALM:thai_realm}
  resource: ${BIZZONE_ID_CLIENT_ID:movie_client_id}
  credentials:
    secret: ${BIZZONE_ID_CLIENT_SECRET:nv4yJkz8IDi0aqeg2lJUhi9PdZAC7tVW}